### ISSUE TITLE
cannot clear a learner's phase successfully

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#1105]
Stephan Weber has left the Guild. I tried to clear his Phase by setting it to "No Phase" in echo, but it doesn't save -- it just reverts to the original value (in this case, 5).

https://app.asana.com/0/139326150873509/440170766072322

**Comment by jeffreywescott** [comment]
Maybe it's just not deployed yet, but ... still not working for me, FWIW.

**Comment by prattsj** [comment]
Yeah, hasn't deployed yet. Some weirdness with a timezone-related thing causing the build to fail. Looking into it now.

**Comment by jeffreywescott** [comment]
[!timezones](https://www.explainxkcd.com/wiki/images/e/e8/supervillain_plan.png)

**Comment by jeffreywescott** [comment]
@prattsj FWIW, I just retried this this morning and it still doesn't work.

**Comment by prattsj** [comment]
Yeah, that's why I reopened. Fixes for the server action handling a null phase and for the awkward time-related test bug are out, and the build is okay, but it revealed another issue with the front-end having to do with graphql and the version we've been using stripping properties w/ `null` values from queries. Last night I ran out of juice before completing the upgrades (which required updates for breaking changes), but it's almost wrapped up now. I'm also adding the missing test for setting the phase to null.
